# Autogenerated wrapper script for ConnectFourSolver_jll for x86_64-unknown-freebsd
export libconnect4jl

using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("ConnectFourSolver")
JLLWrappers.@declare_library_product(libconnect4jl, "libconnect4jl.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libconnect4jl,
        "lib/libconnect4jl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
